#
# Example config.toml for the inLimbo project.
# 
# URL: https://github.com/nots1dd/inLimbo (develop branch) 
# Author: Siddharth Karanam (nots1dd)
# 

[library]
name = "Songs"
directory = "/home/s1dd/Downloads/Songs/" # just an example

[fuzzy]
max_dist = 3

# NOTE: Only `Tab`, `Escape`, `Enter/Return` and `Space` are accepted as special chars
[keybinds.cmdline]
play_pause = "p"
search_title = "/"
search_artist = "a"
next_track = "n"
prev_track = "b"
random_track = "x"
restart_track = "r"
seek_back = "j"
seek_fwd = "k"
vol_up = "="
vol_down = "-"
quit = "q"

[colors.cmdline]
bg = "#0B0F14"
fg = "#9CF1F0"
accent = "#6F8FAF"
warning = "#FFC800"
error = "#FF3C3C"
success = "#6C948B"

[misc.cmdline]
seek_duration = 5

[keybinds.raylib]
play_pause = "p"
next_track = "n"
prev_track = "b"
random_track = "x"
restart = "r"
seek_back = "j"
seek_fwd = "k"
vol_up = "="
vol_down = "-"
quit = "q"

[colors.raylib]
bg = "#0B0F14"
fg = "#9CF1F0"
accent = "#6F8FAF"
warning = "#FFC800"
error = "#FF3C3C"
success = "#6C948B"
